config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :fighters, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :battles, only: [:index, :new, :show, :create] do
    get :result, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :your_fighter, class_name: "Fighter"
  belongs_to :enemy_fighter, class_name: "Fighter"
  belongs_to :winner, class_name: "Fighter"

  def loser
    self.winner == self.your_fighter ? self.enemy_fighter : self.your_fighter
  end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :left_hand, class_name: "Fighter", foreign_key: "left_hand_id"
  has_many :right_hand, class_name: "Fighter", foreign_key: "right_hand_id"

  def self.can_handle(fighter)
    where("level <= #{fighter.exp}")
  end
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :left_hand, class_name: "Equipment"
  belongs_to :right_hand, class_name: "Equipment"

  validates :name, presence: true, allow_blank: false, format: {
    with: /\A[a-zA-Z]+\z/,
    message: "must be realistic..."
  }, length: { maximum: 13 }

  validates :health, :attack, format: { with: /\A\d+\z/, message: "must be number" }
  validate :max_health_and_attack, on: :create
  validate :min_health_and_attack, on: :create

  has_many :your_fighter, class_name: "Battle", foreign_key: "your_fighter_id", dependent: :destroy
  has_many :enemy_fighter, class_name: "Battle", foreign_key: "enemy_fighter_id", dependent: :destroy
  has_many :winner, class_name: "Battle", foreign_key: "winner_id", dependent: :destroy


  before_save :capitalize_name
  after_initialize :add_hands, if: :new_record?

  def max_health_and_attack
    if attack.class == Integer && health.class == Integer && (attack + health) != 11
      errors.add(:attack, " + health points must be equal to 11 !")
      errors.add(:health, " + attack points must be equal to 11 !")
    else
      return true
    end
  end

  def min_health_and_attack
    if attack && attack.zero? || health && health.zero?
      errors.add(:attack, "no pacifist here")
      errors.add(:health, "you need to live first (more than 0)")
    else
      return true
    end
  end

  def capitalize_name
    name.capitalize!
  end

  def battle_count
    Battle.where(your_fighter: self).or(Battle.where(enemy_fighter: self)).count
  end

  def defense_equipment
    if right_hand.mode == "armor" && left_hand.mode == "armor"
      return left_hand.value + right_hand.value
    elsif left_hand.mode == "armor"
      return left_hand.value
    elsif right_hand.mode == "armor"
      return right_hand.value
    else
      return nil
    end
  end

  def offense_equipment
    if right_hand.mode == "attack" && left_hand.mode == "attack"
      return left_hand.value + right_hand.value
    elsif left_hand.mode == "attack"
      return left_hand.value
    elsif right_hand.mode == "attack"
      return right_hand.value
    else
      return nil
    end
  end
end

def add_hands
  self.left_hand = Equipment.first
  self.right_hand = Equipment.first
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_battle, only: %i[create new]

  def index
    @battles = Battle.all
  end

  def new
  end

  def create
    @battle.winner_id = params[:battle][:winner_id]
    @battle.remaining_health = params[:battle][:remaining_health]
    @battle.save
    @battle.winner.victories += 1
    @battle.winner.exp += 1
    @battle.loser.exp += 0.5
    @battle.winner.save
    @battle.loser.save
    redirect_to result_battle_path(@battle)
  end

  def result
    @battle = Battle.find(params[:id])
  end

  private

  def set_battle
    @battle = Battle.new
    @battle.enemy_fighter_id = params["battle"]["enemy_fighter_id"]
    @battle.your_fighter_id = params["battle"]["your_fighter_id"]
  end

  def battle_params
    params.require(:battle).permit(:enemy_fighter_id, :your_fighter_id, :winner_id)
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_fighter, only: %i[show update]

  def index
    @fighters = Fighter.all.order('exp DESC')
    @battle = Battle.new
  end

  def show
    @all_equipments = Equipment.all
    @equipments = Equipment.can_handle(@fighter)
  end

  def new
    @fighter = Fighter.new
  end

  def create
    @fighter = Fighter.create(fighter_params)
    if @fighter.save
      redirect_to fighters_path
    else
      render :new
    end
  end

  def update
    @fighter.update(fighter_params)
    respond_to do |format|
      if @fighter.save
        format.html { redirect_to fighter_path(@fighter) }
        format.js
      else
        format.html { redirect_to fighters_path }
      end
    end
  end

  def destroy
  end

  private

  def set_fighter
    @fighter = Fighter.find(params[:id])
  end

  def fighter_params
    params.require(:fighter).permit(:name, :health, :attack, :left_hand_id, :right_hand_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/battles/_index.html.erb
<div class="index-fighter">
  <div class="index-battle-photo">
    <% if !fighter.photo.nil? %>
      <%= cl_image_tag fighter.photo, height: 110, width: 110, crop: :fill %>
    <% end %>
  </div>
  <div class="fighter-name">
    <p><%= fighter.name %></p>
  </div>
</div>

app/views/battles/_new.html.erb
<div class="name">
  <%= fighter.name %>
</div>
<div class="battle-photo">
  <% if !fighter.photo.nil? %>
    <%= cl_image_tag fighter.photo, height: 200, width: 200, crop: :fill %>
  <% end %>
</div>
<div class="stats">
  <div class="health" data-health="<%= fighter.id %>">
    <div class="health-count">
      <div class="base-health">
        <%= fighter.health %>
      </div>
      <div>
        <%= image_tag "heart.PNG", class: "heart-icon" %>
      </div>
    </div>
  </div>

  <% if fighter.defense_equipment && fighter.defense_equipment > 0 %>
    <div class="armor-count">
      <%= fighter.defense_equipment %>
      <%= image_tag "shield.PNG", class: "heart-icon" %>
    </div>
  <% end %>

  <div class="attack" data-attack="<%= fighter.id %>">
    <div class="attack-count">
      <div class="base-attack">
        <%= fighter.attack %>
      </div>
      <% if fighter.offense_equipment && fighter.offense_equipment > 0%>
        <p> + </p>
        <div class="weapon">
          <%= fighter.offense_equipment %>
        </div>
      <% end %>
      <div>
        <%= image_tag "sword.PNG", class: "sword-icon" %>
      </div>
    </div>
  </div>
</div>

app/views/battles/_show.html.erb
<div class="name">
  <%= fighter.name %>
</div>
<div class="stats">
  <div class="health" data-health="<%= fighter.id %>">
    <div class="health-count">
      <%= fighter.health %>
    </div>
    <div>
      <%= image_tag "heart.PNG", class: "heart-icon" %>
    </div>
  </div>
  <div class="attack" data-attack="<%= fighter.id %>">
    <div class="attack-count">
      <%= fighter.attack %>
    </div>
    <div>
      <%= image_tag "sword.PNG", class: "sword-icon" %>
    </div>
  </div>
</div>

app/views/battles/index.html.erb
<div class="container">
  <div class="all-battles">
    <div class="won-lost">
      <h1>WON</h1>
      <h1>...</h1>
      <h1>LOST</h1>
    </div>
    <% @battles.each do |battle| %>
      <div class="index-battle">
        <%= render "index", fighter: battle.winner %>
        <div class="index-vs">
          <div class="vs-sign">
            <p>VS</p>
          </div>
          <div class="vs-infos">
            <p><%= I18n.l(battle.created_at, format: :short) %> </p>
          </div>
        </div>
        <%= render "index", fighter: battle.loser %>
      </div>
    <% end %>
  </div>
</div>

app/views/battles/new.html.erb
<div class="container">
  <div class="battleground">
    <div class="around">
      <div class="fighter" id="your-fighter" data-fighter="<%= @battle.your_fighter.id %>">
        <%= render "new", fighter: @battle.your_fighter %>
      </div>
    </div>
    <div class="around">
      <div class="fighter" id="enemy-fighter" data-fighter="<%= @battle.enemy_fighter.id %>">
        <%= render "new", fighter: @battle.enemy_fighter %>
      </div>
    </div>
  </div>
  <div class="result">
    <%= form_for @battle, url: {action: :create} do |f| %>
      <%= f.hidden_field :winner_id, input_html: {
        value: '',
        id: "winner"
      } %>
      <%= f.hidden_field :your_fighter_id, input_html: {
        value: @battle.your_fighter
      } %>
      <%= f.hidden_field :enemy_fighter_id, input_html: {
        value: @battle.enemy_fighter
      } %>
      <%= f.hidden_field :remaining_health, input_html: {
        value: '',
        id: "health-remain"
      } %>
      <%= f.submit "SEE THE RESULT!", class: "submit-battle"%>
    <% end %>
  </div>
</div>

app/views/battles/result.html.erb
<div class="container">
    <div class="result-battle-infos">
      <div class="result-title">
        <h1><%= @battle.winner.name %> won the fight !</h1>
      </div>
      <div class="fight-details">
        <% if @battle.remaining_health > 7 %>
          <h5><%= @battle.winner.name %> destroyed <%= @battle.loser.name %></h5>
        <% elsif @battle.remaining_health < 3 %>
          <h5>Close one... <%= @battle.winner.name %> only has <%= @battle.remaining_health%> health points left </h5>
        <% else %>
          <h5>He defeated <%= @battle.loser.name %> with <%= @battle.remaining_health %> health points remaining  </h5>
        <% end %>
      </div>
      <div class="winner-details">
        <h2><%= @battle.winner.name %> levels up and can equip new gears!! </h2>
        <div class="winner-link">
          <%= link_to "You can now give stuff to this fighter", fighter_path(@battle.winner)  %>
        </div>
      </div>
    </div>
</div>

app/views/battles/show.html.erb
<div class="container">
  <div class="battleground">
    <div class="fighter" id="your-fighter" data-fighter="<%= @battle.your_fighter.id %>">
      <%= render "show", fighter: @battle.your_fighter %>
    </div>
    <div class="fighter" id="enemy-fighter" data-fighter="<%= @battle.enemy_fighter.id %>">
      <%= render "show", fighter: @battle.enemy_fighter %>
    </div>
  </div>
  <div class="result">
    <%= form_for @battle do |f| %>
      <%= f.hidden_field :winner_id, input_html: {
        value: '',
        id: "winner"
      } %>
      <%= f.submit "SEE THE RESULT! "%>
    <% end %>
  </div>
</div>

app/views/fighters/_index.html.erb
<div class="fighter-card" >
  <div class="name">
    <p><%= link_to fighter.name, fighter_path(fighter)%> (lvl:<%= fighter.exp %>) </p>
  </div>
  <div class="stats">
    <div class="stats-numbers">
     <p><%= image_tag "heart.PNG", class: "heart-icon" %>
      <% if fighter.defense_equipment && !fighter.defense_equipment.zero?%>
        <%= fighter.health%><span class="bonus-armor">+<%=fighter.defense_equipment %></span></p>
      <% else %>
        <%= fighter.health%></p>
      <% end %>
     <p><%= image_tag "sword.PNG", class: "sword-icon" %>
      <% if fighter.offense_equipment && !fighter.offense_equipment.zero?%>
        <%= fighter.attack%><span class="bonus-att">+<%=fighter.offense_equipment %></span> </p>
      <% else %>
        <%= fighter.attack%></p>
      <% end %>
    </div>
    <div class="photo">
      <% if !fighter.photo.nil? %>
        <%= cl_image_tag fighter.photo, height: 150, width: 150, crop: :fill %>
      <% end %>
    </div>
  </div>
  <button class="select-fighter" data-fighter="<%= fighter.id %>" ><strong>SELECT THIS FIGHTER</strong></button>
</div>

app/views/fighters/_show.html.erb
<div class="show-fighter">
  <div class="show-title">
    <div class="name-level">
      <p><%= fighter.name %></p>
      <p>Level : <%= fighter.exp %></p>
    </div>
    <div class="win-ratio">
      <p><%= fighter.victories %> win(s) / <%= fighter.battle_count %> </p>
    </div>
  </div>
  <div class="show-photo">
    <% if !fighter.photo.nil? %>
      <%= cl_image_tag fighter.photo, height: 200, width: 200, crop: :fill %>
    <% end %>
  </div>
  <div class="characteristics">
    <div class="base">
      <p><%= image_tag "heart.PNG", class: "heart-icon" %>
       <%= fighter.health %>
       <% if fighter.defense_equipment && !fighter.defense_equipment.zero? %>
          <span class="show-bonus-armor">+ <%= fighter.defense_equipment %> <%= image_tag "shield.PNG", class: "heart-icon" %></span>
       <% end %>
      </p>
      <p><%= image_tag "sword.PNG", class: "sword-icon" %>
       <%= fighter.attack %>
       <% if fighter.offense_equipment && !fighter.offense_equipment.zero? %>
          <span class="show-bonus-attack">+ <%= fighter.offense_equipment %></span>
       <% end %></p>
    </div>
    <div class="equipment">
      <p><%= fighter.left_hand.name %></p>
      <p><%= fighter.right_hand.name %></p>
    </div>
  </div>
</div>

app/views/fighters/edit.html.erb
<%= simple_form_for @fighter, method: :patch do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/fighters/index.html.erb
<div class="container">

  <div>
    <h2 class="title">SELECT TWO FIGHTERS THEN START THE BATTLE!</h2>
  </div>

  <div class="index-content">
    <div class="fighter-cards">
      <% @fighters.each do |fighter| %>
        <%= render "index", fighter: fighter %>
      <% end %>
    </div>

    <div class="index-links">
      <%= link_to "Create your own fighter", new_fighter_path, class: "link" %>
      <%= link_to "See battle history", battles_path, class: "link"  %>
      <div class="create-battle">
        <%= form_for @battle, url: {controller: "battles", action: :new}, method: :get do |f| %>
          <%= f.hidden_field :your_fighter_id, input_html: {
            value: '',
            id: "your-fighter"
          } %>
          <%= f.hidden_field :enemy_fighter_id, input_html: {
            value: '',
            id: "enemy-fighter"
          } %>
          <%= f.submit "FIGHT", class: "battle-link" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fighters/new.html.erb
<div class="container">
  <div class="new-form">
    <%= simple_form_for @fighter do |f| %>
      <%= f.input :name %>
      <%= f.input :health %>
      <%= f.input :attack %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit, "CREATE CHARACTER", class: "submit-fighter" %>
    <% end %>
  </div>
</div>

app/views/fighters/show.html.erb
<div class="container">
  <div class="show-content">
    <%= render "show", fighter: @fighter %>
    <div class="shop">
      <div class="available">
        <div class="presentation">
          <p><strong>Change your gear</strong></p>
        </div>
        <div class="gears">
          <ul>
            <% Equipment.where.not(name: "Bare Knuckles").each do |equipment| %>
              <li class=""><%= equipment.name %>(Level <%= equipment.level %>): + <%= "#{equipment.value} #{equipment.mode}" %></li>
            <% end %>
          </ul>
        </div>
      </div>


      <div class="upgrade-gear-message">
        <p>Stuff your character by changing his gear below</p>
      </div>

      <%= simple_form_for @fighter, method: :patch, remote: true do |f| %>
        <%= f.label :left_hand_id %>
        <%= f.collection_select :left_hand_id, @equipments, :id, :name, {}, {class: 'equipment-selector'}%>
        <%= f.label :right_hand_id %>
        <%= f.collection_select :right_hand_id, @equipments, :id, :name, {}, {class: 'equipment-selector'} %>
      <% end %>
    </div>
  </div>
  <div class="show-links">
    <%= link_to "SAVE AND GO BACK", fighters_path  %>
  </div>
</div>

app/views/fighters/update.js.erb
function refreshFighter(innerHTML) {
  const showContent = document.querySelector('.show-content')
  document.querySelector('.show-fighter').remove()
  showContent.insertAdjacentHTML('afterbegin', innerHTML)
}

refreshFighter('<%= j render "fighters/show", fighter: @fighter %> ')
console.log("hello")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Suez+One&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="homepage">
    <div class="welcome-title">
      <p>WELCOME TO WEBBRAWL</p>
      <p class="subtitle">International random fights arena</p>
    </div>
    <div class="app-description">
      <p>Join the arena and train your fighters OR those of other players. You start fighting bare handed but with each fight you gain levels and can carry new equipments ! Unlocked gear will help hitting harder and blocking attacks</p>
    </div>
  </div>
</div>
<div class="home-banner">
  <div class="info-icons">
    <div class="create-fighter">
      <%= image_tag("custom-hero.PNG") %>
      <p>Create fighters of your choice</p>
    </div>
    <div class="random-fights">
      <%= image_tag("clash.PNG") %>
      <p>Fight each other</p>
    </div>
    <div class="stuff-your-fighter">
      <%= image_tag("shield-sword.PNG") %>
      <p>Gear them as you like</p>
    </div>
  </div>
  <%= link_to "See fighters", fighters_path, class: "fighters-link"  %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/fighters", class: "navbar-brand" do %>
    <%= image_tag "sword.PNG" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <% end %>
    </ul>
  </div>
</div>